[package]
name = "pumpfun_global"
# description = "Utility crate for values used in the pumpfun instructions"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-sdk = { workspace = true }
spl-token = "8.0.0"
spl-associated-token-account = "7.0.0"
spl-token-2022 = "9.0.0"
